"""Cursor project-rule integration.

Official contract (https://cursor.com/docs/rules, Aug 2026):
- Project rules live in `.cursor/rules/*.mdc` with YAML frontmatter.
- `alwaysApply: true` includes the rule in every Agent session.
- Rules may `@`-reference files so the generated snapshot stays short.
- Cursor has no SessionStart hook; generated files are refreshed on
  init / approve / reject / suggest.
"""

from __future__ import annotations

from pathlib import Path

from canon.constants import INJECTION_FILENAME, MANAGED_BEGIN, MANAGED_END, PROJECT_DIRNAME
from canon.gitutil.runner import which

RULE_REL = Path(".cursor") / "rules" / "canon.mdc"


def detect_cursor(repo_root: Path) -> bool:
    return (repo_root / ".cursor").is_dir() or which("cursor") is not None


def _rule_text() -> str:
    return (
        "---\n"
        "description: Canon governed project decisions\n"
        "alwaysApply: true\n"
        "---\n"
        f"<!-- {MANAGED_BEGIN} -->\n"
        "\n"
        "# Canon — Project Decisions\n"
        "\n"
        "These are confirmed project decisions. Treat them as authoritative.\n"
        "Do not re-adopt a rejected or superseded approach.\n"
        "If no confirmed decision applies, say: I have no confirmed decision on this.\n"
        "\n"
        f"Read and follow @{PROJECT_DIRNAME}/{INJECTION_FILENAME} when it exists.\n"
        "That file is generated by Canon. Do not invent missing decisions.\n"
        "\n"
        f"<!-- {MANAGED_END} -->\n"
    )


def install_cursor(repo_root: Path) -> list[str]:
    path = repo_root / RULE_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    desired = _rule_text()
    if path.is_file() and path.read_text(encoding="utf-8") == desired:
        return ["Cursor Canon rule already present"]
    path.write_text(desired, encoding="utf-8")
    return [f"Wrote {RULE_REL} (always-apply project rule)"]


def uninstall_cursor(repo_root: Path) -> list[str]:
    path = repo_root / RULE_REL
    if path.is_file() and MANAGED_BEGIN in path.read_text(encoding="utf-8"):
        path.unlink()
        return [f"Removed {RULE_REL}"]
    return []


def cursor_status(repo_root: Path) -> tuple[bool, str]:
    path = repo_root / RULE_REL
    if path.is_file() and MANAGED_BEGIN in path.read_text(encoding="utf-8"):
        return True, "Always-apply project rule installed"
    return False, "Cursor Canon rule not installed"
